require:
  - rubocop-rails


AllCops:
  Exclude:
    - 'db/*'
    - 'spec/support/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  ExcludedMethods: ['before', 'describe', 'context', 'it']

Metrics/MethodLength:
  Max: 25
  ExcludedMethods: ['before', 'describe', 'context', 'it']

Layout/LineLength:
  Max: 180

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false