require:
  - rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 25
  ExcludedMethods: ['before', 'describe', 'context', 'it']

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false